### ISSUE TITLE
Problems creating rmw app

### ISSUE THREAD

**Issue by tmasunda** [TarikHuber/rmw-shell#17]
I am getting the following error when trying to create an app using rmw:
error Couldn't find any versions for "rmw-react-scripts" that matches "latest" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue. 

I am using node version 10.11.0 

please assist.

**Comment by TarikHuber** [comment]
Hi @tmasunda . Have you tried using it without the offline flag? And have you tried using just npm (just to see the differences)?

**Comment by Kings3D** [comment]
Hi Tarik, i finally managed to install using the offline flag and as admin on my windows 10 machine. Thanks. Please close.
