### ISSUE TITLE
[Question] Are there any breaking changes for RMW?

### ISSUE THREAD

**Issue by zomars** [TarikHuber/rmw-shell#2]
Also, is there a specific reason to separate the shell from the project? Thanks again!

**Comment by TarikHuber** [comment]
Hi @zomars ,

React Most Wanted was a boilerplate so there was nothing to break. You could always start from it but from that point on you had to manually sync my updates to RMW to your projects. `rmw-shell` should change that. It has inside the shell of RMW and when I now make some updates to `rmw-shell` you can add them to your own project by just updating the npm module.

But yes, React Most Wanted changed itself drastically but for the good. There is about 90 % less code in it and all of the code left over are just examples how you can configure your own project. It would work even without any configs. Here is article I wrote about it: [Beyond create-react-app (CRA)](https://codeburst.io/beyond-create-react-app-cra-a2063196a124)
