### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by TarikHuber** [TarikHuber/rmw-shell#24]
Even if there is a default theme set to the initial configs the first visit starts with the blue theme from the RMW demo.

**Comment by ingen0s** [comment]
This seems to still be an open issue - have been trying to debug

**Comment by ingen0s** [comment]
Solved: Can not name your default them as "default" - needs to be a unique name :)

**Comment by ingen0s** [comment]
defaults back to blue on sign out

**Comment by TarikHuber** [comment]
Hi @ingen0s 

Try it with this configs:

```
  initial_state: {
    themeSource: {
      isNightModeOn: true,
      source: 'default'
    },
    locale: 'de'
  },
```
