### ISSUE TITLE
Cannot resolve dependency issue.

### ISSUE THREAD

**Issue by khubo** [TarikHuber/rmw-shell#6]
when the package is being update i am geting the error
`Can't resolve 'react-mic' in '<path>/node_modules/rmw-shell/es/containers/ChatMessages'`
Could it because everything is under devDependency instead of dependency?

**Comment by TarikHuber** [comment]
Did you try to install react-mic with 'npm i react-mic' it is a peer dependency that was added after the release.

**Comment by TarikHuber** [comment]
@khubo did it work out?

**Comment by khubo** [comment]
@TarikHuber i tried that, but turns out 'react-mic' is not the only one.( react-player etc.) Dont you think it will be better fixed at package level. ?

**Comment by TarikHuber** [comment]
@khubo Those two should be it ;)
It's just that I don't like to have all those modules directly as dependency. All my npm modules have just peer dependencies. You come in such an error only when you upgrade to a new version and there is a new peer dependencie like in your case now. As a breaking change I should take more care about the npm versioning. Expirienced npm users recognize this error very fast. 

If we would set all the modules as dependencies and not peer dependencies everyone who uses rmw-shell would have to wait on us to update rmw-shell for bugfixes in those dependencies.
